In [4]:
# Chapter 5 Exercise
# Question 1
import numpy as np
a = np.array([[1,2,3], [4,5,6]])
b = a.flatten() * 2
print (type(a), a)
print (type(b), b)


<class 'numpy.ndarray'> [[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'> [ 2  4  6  8 10 12]


In [6]:
# Question 3
import numpy as np
a = np.arange(5, 31, 5)
print (type(a), a)


<class 'numpy.ndarray'> [ 5 10 15 20 25 30]


In [18]:
# Question 4
import numpy as np
a = np.zeros([2,3], dtype=int)
print (type(a), a)
print ("shape :", a.shape)
print ("ndim :", a.ndim)
print ("dtype :", a.dtype)
print ("size :", a.size)

<class 'numpy.ndarray'> [[0 0 0]
 [0 0 0]]
shape : (2, 3)
ndim : 2
dtype : int32
size : 6


In [24]:
# Question 5
import numpy as np
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
print (type(a), a)
print (a[1])
print (a[2,2])
print (a[1:3])
print (a[a<=5])

<class 'numpy.ndarray'> [[1 2 3]
 [4 5 6]
 [7 8 9]]
[4 5 6]
9
[[4 5 6]
 [7 8 9]]
[1 2 3 4 5]
