In [9]:
# Numpy Operator
import numpy as np
aArr = np.arange(1,5)
bArr = np.ones(4)
print (type(aArr), aArr)
print (type(bArr), bArr)
print (aArr, bArr)
print (aArr + bArr)
print (aArr - bArr)
print (aArr > bArr)

<class 'numpy.ndarray'> [1 2 3 4]
<class 'numpy.ndarray'> [1. 1. 1. 1.]
[1 2 3 4] [1. 1. 1. 1.]
[2. 3. 4. 5.]
[0. 1. 2. 3.]
[False  True  True  True]


In [19]:
# Numpy *, /, //, %
import numpy as np
aArr = np.random.randint(11, size = 4)
print (type(aArr) , aArr)
print (aArr + 2)
print (aArr * 2)
print (aArr / 2)
print (aArr // 2)
print (aArr % 2)

<class 'numpy.ndarray'> [6 0 3 4]
[8 2 5 6]
[12  0  6  8]
[3.  0.  1.5 2. ]
[3 0 1 2]
[0 0 1 0]


In [38]:
# Numpy Universial Method
import numpy as np
aArr = np.random.randint(-10, 11, size=5)
print (type(aArr), aArr)
print ("max :", np.max(aArr))
print ("min :", np.min(aArr))
print ("sum :", np.sum(aArr))
print ("mean :", np.mean(aArr))
print ("var :", np.var(aArr))
print ("std :", np.std(aArr))
print ("abs :", np.abs(aArr))
print ("rint :", np.rint(aArr))
print ("floor :", np.floor(aArr))
# print ("sqrt :", np.sqrt(aArr))


<class 'numpy.ndarray'> [-5 -6  3 -7  1]
max : 3
min : -7
sum : -14
mean : -2.8
var : 16.16
std : 4.019950248448356
abs : [5 6 3 7 1]
rint : [-5. -6.  3. -7.  1.]
floor : [-5. -6.  3. -7.  1.]


In [48]:
# Numpy Array Practice
import numpy as np
aScore = np.array([20, 30, 60])
bScore = np.array([60, 40, 90])
print (type(aScore), aScore)
print (type(bScore), bScore)
cTotal = aScore + bScore
dAvg = cTotal / 2
print (type(cTotal), cTotal)
print (type(dAvg), dAvg)
print ("a 평균 :", np.mean(aScore))

<class 'numpy.ndarray'> [20 30 60]
<class 'numpy.ndarray'> [60 40 90]
<class 'numpy.ndarray'> [ 80  70 150]
<class 'numpy.ndarray'> [40. 35. 75.]
a 평균 : 36.666666666666664
