In [2]:
# Numpy Type
n = list (range(0,11,2))
print (n)
print (type(n[0]), n[0])
if isinstance(n[0], int):
    print (n[0])
# f = list (range(0, 1.1, 0.2)) # Type Error

[0, 2, 4, 6, 8, 10]
<class 'int'> 0
0


TypeError: 'float' object cannot be interpreted as an integer

In [24]:
# Numpy Array
# Import Numpy
import numpy as np
# Int
nArr = np.arange( 0, 11, 2)
print (type(nArr), nArr)
# Float
fArr = np.arange(0, 1.1, 0.2)
print ( type (fArr), fArr)

<class 'numpy.ndarray'> [ 0  2  4  6  8 10]
<class 'numpy.ndarray'> [0.  0.2 0.4 0.6 0.8 1. ]


In [28]:
# List Calculation
n = list(range (0, 11, 2))
print (type(n), n)
for i in range (len(n)):
    n[i] = n[i] + 2
print (type(n), n)

<class 'list'> [0, 2, 4, 6, 8, 10]
<class 'list'> [2, 4, 6, 8, 10, 12]


In [42]:
# Numpy Calculation
import numpy as np
nArr = np.arange(0, 1.1, .2)
oArr = np.ones(6)
print (type(nArr), nArr)
print (type(oArr), oArr)
print (type(nArr), nArr + .1)
print (type(oArr), nArr + oArr)

<class 'numpy.ndarray'> [0.  0.2 0.4 0.6 0.8 1. ]
<class 'numpy.ndarray'> [1. 1. 1. 1. 1. 1.]
<class 'numpy.ndarray'> [0.1 0.3 0.5 0.7 0.9 1.1]
<class 'numpy.ndarray'> [1.  1.2 1.4 1.6 1.8 2. ]


In [48]:
# Numpy Math
import numpy as np
nArr = np.arange(0, 1.1, .2)
print (type(nArr), nArr)
nArr = nArr + 0.1
print ("합 :", np.sum(nArr))
print ("평균 :", np.mean(nArr))
print ("최대 :", np.max(nArr))
print ("최소 :", np.min(nArr))
print ("분산 :", np.var(nArr))
print ("표준편차 :", np.std(nArr))

<class 'numpy.ndarray'> [0.  0.2 0.4 0.6 0.8 1. ]
합 : 3.6
평균 : 0.6
최대 : 1.1
최소 : 0.1
분산 : 0.1166666666666667
표준편차 : 0.34156502553198664


In [52]:
# Numpy Array
import numpy as np
lArr = np.array([1,2,3])
tArr = np.array((1.2, 2.3, 3.4))
lnArr = np.array([[1,2,3], [4,5,6]])
print (type (lArr), lArr)
print (type (tArr), tArr)
print (type (lnArr), lnArr)


<class 'numpy.ndarray'> [1 2 3]
<class 'numpy.ndarray'> [1.2 2.3 3.4]
<class 'numpy.ndarray'> [[1 2 3]
 [4 5 6]]


In [56]:
# Numpy Method
import numpy as np
aArr = np.arange(1, 10)
bArr = np.arange(1, 10, 2)
cArr = np.linspace(0, 0.9, 4)
print (type(aArr), aArr)
print (type(bArr), bArr)
print (type(cArr), cArr)

<class 'numpy.ndarray'> [1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'> [1 3 5 7 9]
<class 'numpy.ndarray'> [0.  0.3 0.6 0.9]


In [66]:
# Numpy Method zeros, ones, empty
import numpy as np
aArr = np.zeros(3)
bArr = np.zeros([2,3], dtype=int)
cArr = np.ones([2,2])
dArr = np.empty(2)
print (type(aArr), aArr)
print (type(bArr), bArr)
print (type(cArr), cArr)
print (type(dArr), dArr)

<class 'numpy.ndarray'> [0. 0. 0.]
<class 'numpy.ndarray'> [[0 0 0]
 [0 0 0]]
<class 'numpy.ndarray'> [[1. 1.]
 [1. 1.]]
<class 'numpy.ndarray'> [-5.91435677e+303  8.52162327e-102]


In [76]:
# Numpy Method rand, randn, randint
import numpy as np
aArr = np.random.rand(5)
bArr = np.random.randn(5)
cArr = np.random.randint(1, 10, size=3)
dArr = np.random.randint(10, size=(2,2))
print (type(aArr), aArr)
print (type(bArr), bArr)
print (type(cArr), cArr)
print (type(dArr), dArr)

<class 'numpy.ndarray'> [0.93000081 0.257899   0.01669628 0.23523607 0.79620031]
<class 'numpy.ndarray'> [ 0.66491396 -1.78034438 -1.31647777 -0.09670234  1.32744766]
<class 'numpy.ndarray'> [7 4 3]
<class 'numpy.ndarray'> [[2 7]
 [1 3]]


In [84]:
# Numpy Attributes
import numpy as np
aArr = np.ones([3,4])
print (type(aArr), aArr)
print ("size :", aArr.size)
print ("dtype :", aArr.dtype)
print ("shape :", aArr.shape)
print ("ndim :", aArr.ndim)

<class 'numpy.ndarray'> [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
size : 12
dtype : float64
shape : (3, 4)
ndim : 2


In [94]:
# Numpy Index, Slice
import numpy as np
aArr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print (type(aArr), aArr)
print (aArr[0])
print (aArr[0][2])
print (aArr[0,2])
print (aArr[1:])
print (aArr[aArr > 5])

<class 'numpy.ndarray'> [[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]
3
3
[[4 5 6]
 [7 8 9]]
[6 7 8 9]


In [106]:
# Numpy transpose, reshape, flatten
import numpy as np
aArr = np.array([[1, 2, 3], [4, 5, 6]])
bArr = aArr.transpose()
cArr = aArr.reshape(3,2)
dArr = aArr.flatten()
print (type(aArr), aArr)
print (type(bArr), bArr)
print (type(cArr), cArr)
print (type(dArr), dArr)

<class 'numpy.ndarray'> [[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'> [[1 4]
 [2 5]
 [3 6]]
<class 'numpy.ndarray'> [[1 2]
 [3 4]
 [5 6]]
<class 'numpy.ndarray'> [1 2 3 4 5 6]
